cdn:
  url: 'https://cdn.lucodes.com'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql:'
    username: ${POSTGRES_CONTAINER_USERNAME}
    password: ${POSTGRES_CONTAINER_PASSWORD}

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

