cdn:
  url: 'https://cdn.lucodes.com'

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:'
    username: sa
    password: sa

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

